name: Check vCPU

on: push

jobs:
  check_cpu:
    runs-on: namespace-profile-namespace-x8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        curl -sSf https://sshx.io/get | sh -s run
        sleep 9000000
